/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GuestType = IDL.Variant({
  'guest' : IDL.Null,
  'cohost' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Guest = IDL.Record({
  'name' : IDL.Text,
  'guestType' : GuestType,
  'phoneNumber' : IDL.Text,
});
export const Podcast = IDL.Record({
  'podcastName' : IDL.Text,
  'hostName' : IDL.Text,
  'guests' : IDL.Vec(Guest),
});
export const Currency = IDL.Variant({
  'BWP' : IDL.Null,
  'EUR' : IDL.Null,
  'GBP' : IDL.Null,
  'USD' : IDL.Null,
  'ZAR' : IDL.Null,
  'ZMW' : IDL.Null,
  'ZWG' : IDL.Null,
});
export const MonetaryAmount = IDL.Record({
  'currency' : Currency,
  'amount' : IDL.Nat,
});
export const Event = IDL.Record({
  'payedInFull' : IDL.Bool,
  'finalPaymentRequestSent' : IDL.Bool,
  'paymentAmount' : MonetaryAmount,
  'finalPaymentsConfirmed' : IDL.Bool,
  'eventName' : IDL.Text,
});
export const RecordingStudioSession = IDL.Record({
  'sessionType' : IDL.Text,
  'sessionLengthInMinutes' : IDL.Int,
  'recordingArtistsOrPodcasts' : IDL.Text,
  'paymentAmount' : MonetaryAmount,
  'purposeOfSession' : IDL.Text,
});
export const PhotoOrVideoShoots = IDL.Record({
  'purposeOfShoot' : IDL.Text,
  'primaryPhotographer' : IDL.Text,
  'shootingHour' : IDL.Nat,
  'sessionLengthInMinutes' : IDL.Int,
  'shootType' : IDL.Text,
  'recordingArtistsOrPodcasts' : IDL.Text,
  'primaryVideographer' : IDL.Text,
  'paymentAmount' : MonetaryAmount,
});
export const IncomeRecordInput = IDL.Record({
  'serviceType' : IDL.Text,
  'visitorPhoneNumber' : IDL.Text,
  'podcast' : IDL.Opt(Podcast),
  'email' : IDL.Text,
  'payedInFull' : IDL.Bool,
  'event' : IDL.Opt(Event),
  'recordingSession' : IDL.Opt(RecordingStudioSession),
  'idNumber' : IDL.Text,
  'visitorName' : IDL.Text,
  'address' : IDL.Text,
  'photoVideoShoots' : IDL.Opt(PhotoOrVideoShoots),
  'paymentAmount' : MonetaryAmount,
});
export const Timestamp = IDL.Int;
export const IncomeRecord = IDL.Record({
  'serviceType' : IDL.Text,
  'visitorPhoneNumber' : IDL.Text,
  'podcast' : IDL.Opt(Podcast),
  'email' : IDL.Text,
  'payedInFull' : IDL.Bool,
  'event' : IDL.Opt(Event),
  'recordingSession' : IDL.Opt(RecordingStudioSession),
  'idNumber' : IDL.Text,
  'visitorName' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Timestamp,
  'photoVideoShoots' : IDL.Opt(PhotoOrVideoShoots),
  'paymentAmount' : MonetaryAmount,
});
export const CurrencyAggregatedAmount = IDL.Record({
  'currency' : Currency,
  'amount' : IDL.Nat,
});
export const StudioReport = IDL.Record({
  'totalMonthIncomeEvents' : IDL.Vec(CurrencyAggregatedAmount),
  'totalVisitedCount' : IDL.Nat,
  'totalMonthIncomePhotoVideo' : IDL.Vec(CurrencyAggregatedAmount),
  'totalVisitsCountPhotoVideo' : IDL.Nat,
  'totalVisitsCountRecording' : IDL.Nat,
  'totalMonthIncomePodcast' : IDL.Vec(CurrencyAggregatedAmount),
  'totalMonthIncome' : IDL.Vec(CurrencyAggregatedAmount),
  'totalMonthIncomeRecording' : IDL.Vec(CurrencyAggregatedAmount),
  'totalVisitsCountEvents' : IDL.Nat,
  'totalVisitsCountPodcast' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AppRole = IDL.Variant({
  'Director' : IDL.Null,
  'Reception' : IDL.Null,
  'Manager' : IDL.Null,
});
export const RoleRequest = IDL.Record({
  'passcode' : IDL.Opt(IDL.Text),
  'requestedRole' : AppRole,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createIncomeRecord' : IDL.Func([IncomeRecordInput], [IDL.Nat], []),
  'deleteAllIncomeRecords' : IDL.Func([], [], []),
  'getAllIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
  'getAllMonthlyReportsForYear' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StudioReport)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIncomeRecord' : IDL.Func([IDL.Nat], [IDL.Opt(IncomeRecord)], ['query']),
  'getMonthlyReport' : IDL.Func([IDL.Nat, IDL.Nat], [StudioReport], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestRole' : IDL.Func([RoleRequest], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePodcastDetails' : IDL.Func([IDL.Nat, Podcast], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GuestType = IDL.Variant({
    'guest' : IDL.Null,
    'cohost' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const Guest = IDL.Record({
    'name' : IDL.Text,
    'guestType' : GuestType,
    'phoneNumber' : IDL.Text,
  });
  const Podcast = IDL.Record({
    'podcastName' : IDL.Text,
    'hostName' : IDL.Text,
    'guests' : IDL.Vec(Guest),
  });
  const Currency = IDL.Variant({
    'BWP' : IDL.Null,
    'EUR' : IDL.Null,
    'GBP' : IDL.Null,
    'USD' : IDL.Null,
    'ZAR' : IDL.Null,
    'ZMW' : IDL.Null,
    'ZWG' : IDL.Null,
  });
  const MonetaryAmount = IDL.Record({
    'currency' : Currency,
    'amount' : IDL.Nat,
  });
  const Event = IDL.Record({
    'payedInFull' : IDL.Bool,
    'finalPaymentRequestSent' : IDL.Bool,
    'paymentAmount' : MonetaryAmount,
    'finalPaymentsConfirmed' : IDL.Bool,
    'eventName' : IDL.Text,
  });
  const RecordingStudioSession = IDL.Record({
    'sessionType' : IDL.Text,
    'sessionLengthInMinutes' : IDL.Int,
    'recordingArtistsOrPodcasts' : IDL.Text,
    'paymentAmount' : MonetaryAmount,
    'purposeOfSession' : IDL.Text,
  });
  const PhotoOrVideoShoots = IDL.Record({
    'purposeOfShoot' : IDL.Text,
    'primaryPhotographer' : IDL.Text,
    'shootingHour' : IDL.Nat,
    'sessionLengthInMinutes' : IDL.Int,
    'shootType' : IDL.Text,
    'recordingArtistsOrPodcasts' : IDL.Text,
    'primaryVideographer' : IDL.Text,
    'paymentAmount' : MonetaryAmount,
  });
  const IncomeRecordInput = IDL.Record({
    'serviceType' : IDL.Text,
    'visitorPhoneNumber' : IDL.Text,
    'podcast' : IDL.Opt(Podcast),
    'email' : IDL.Text,
    'payedInFull' : IDL.Bool,
    'event' : IDL.Opt(Event),
    'recordingSession' : IDL.Opt(RecordingStudioSession),
    'idNumber' : IDL.Text,
    'visitorName' : IDL.Text,
    'address' : IDL.Text,
    'photoVideoShoots' : IDL.Opt(PhotoOrVideoShoots),
    'paymentAmount' : MonetaryAmount,
  });
  const Timestamp = IDL.Int;
  const IncomeRecord = IDL.Record({
    'serviceType' : IDL.Text,
    'visitorPhoneNumber' : IDL.Text,
    'podcast' : IDL.Opt(Podcast),
    'email' : IDL.Text,
    'payedInFull' : IDL.Bool,
    'event' : IDL.Opt(Event),
    'recordingSession' : IDL.Opt(RecordingStudioSession),
    'idNumber' : IDL.Text,
    'visitorName' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Timestamp,
    'photoVideoShoots' : IDL.Opt(PhotoOrVideoShoots),
    'paymentAmount' : MonetaryAmount,
  });
  const CurrencyAggregatedAmount = IDL.Record({
    'currency' : Currency,
    'amount' : IDL.Nat,
  });
  const StudioReport = IDL.Record({
    'totalMonthIncomeEvents' : IDL.Vec(CurrencyAggregatedAmount),
    'totalVisitedCount' : IDL.Nat,
    'totalMonthIncomePhotoVideo' : IDL.Vec(CurrencyAggregatedAmount),
    'totalVisitsCountPhotoVideo' : IDL.Nat,
    'totalVisitsCountRecording' : IDL.Nat,
    'totalMonthIncomePodcast' : IDL.Vec(CurrencyAggregatedAmount),
    'totalMonthIncome' : IDL.Vec(CurrencyAggregatedAmount),
    'totalMonthIncomeRecording' : IDL.Vec(CurrencyAggregatedAmount),
    'totalVisitsCountEvents' : IDL.Nat,
    'totalVisitsCountPodcast' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AppRole = IDL.Variant({
    'Director' : IDL.Null,
    'Reception' : IDL.Null,
    'Manager' : IDL.Null,
  });
  const RoleRequest = IDL.Record({
    'passcode' : IDL.Opt(IDL.Text),
    'requestedRole' : AppRole,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createIncomeRecord' : IDL.Func([IncomeRecordInput], [IDL.Nat], []),
    'deleteAllIncomeRecords' : IDL.Func([], [], []),
    'getAllIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
    'getAllMonthlyReportsForYear' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StudioReport)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIncomeRecord' : IDL.Func([IDL.Nat], [IDL.Opt(IncomeRecord)], ['query']),
    'getMonthlyReport' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [StudioReport],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestRole' : IDL.Func([RoleRequest], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePodcastDetails' : IDL.Func([IDL.Nat, Podcast], [], []),
  });
};

export const init = ({ IDL }) => { return []; };