/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'Director' : null } |
  { 'Reception' : null } |
  { 'Manager' : null };
export type Currency = { 'BWP' : null } |
  { 'EUR' : null } |
  { 'GBP' : null } |
  { 'USD' : null } |
  { 'ZAR' : null } |
  { 'ZMW' : null } |
  { 'ZWG' : null };
export interface CurrencyAggregatedAmount {
  'currency' : Currency,
  'amount' : bigint,
}
export interface Event {
  'payedInFull' : boolean,
  'finalPaymentRequestSent' : boolean,
  'paymentAmount' : MonetaryAmount,
  'finalPaymentsConfirmed' : boolean,
  'eventName' : string,
}
export interface Guest {
  'name' : string,
  'guestType' : GuestType,
  'phoneNumber' : string,
}
export type GuestType = { 'guest' : null } |
  { 'cohost' : null } |
  { 'assistant' : null };
export interface IncomeRecord {
  'serviceType' : string,
  'visitorPhoneNumber' : string,
  'podcast' : [] | [Podcast],
  'email' : string,
  'payedInFull' : boolean,
  'event' : [] | [Event],
  'recordingSession' : [] | [RecordingStudioSession],
  'idNumber' : string,
  'visitorName' : string,
  'address' : string,
  'timestamp' : Timestamp,
  'photoVideoShoots' : [] | [PhotoOrVideoShoots],
  'paymentAmount' : MonetaryAmount,
}
export interface IncomeRecordInput {
  'serviceType' : string,
  'visitorPhoneNumber' : string,
  'podcast' : [] | [Podcast],
  'email' : string,
  'payedInFull' : boolean,
  'event' : [] | [Event],
  'recordingSession' : [] | [RecordingStudioSession],
  'idNumber' : string,
  'visitorName' : string,
  'address' : string,
  'photoVideoShoots' : [] | [PhotoOrVideoShoots],
  'paymentAmount' : MonetaryAmount,
}
export interface MonetaryAmount { 'currency' : Currency, 'amount' : bigint }
export interface PhotoOrVideoShoots {
  'purposeOfShoot' : string,
  'primaryPhotographer' : string,
  'shootingHour' : bigint,
  'sessionLengthInMinutes' : bigint,
  'shootType' : string,
  'recordingArtistsOrPodcasts' : string,
  'primaryVideographer' : string,
  'paymentAmount' : MonetaryAmount,
}
export interface Podcast {
  'podcastName' : string,
  'hostName' : string,
  'guests' : Array<Guest>,
}
export interface RecordingStudioSession {
  'sessionType' : string,
  'sessionLengthInMinutes' : bigint,
  'recordingArtistsOrPodcasts' : string,
  'paymentAmount' : MonetaryAmount,
  'purposeOfSession' : string,
}
export interface RoleRequest {
  'passcode' : [] | [string],
  'requestedRole' : AppRole,
}
export interface StudioReport {
  'totalMonthIncomeEvents' : Array<CurrencyAggregatedAmount>,
  'totalVisitedCount' : bigint,
  'totalMonthIncomePhotoVideo' : Array<CurrencyAggregatedAmount>,
  'totalVisitsCountPhotoVideo' : bigint,
  'totalVisitsCountRecording' : bigint,
  'totalMonthIncomePodcast' : Array<CurrencyAggregatedAmount>,
  'totalMonthIncome' : Array<CurrencyAggregatedAmount>,
  'totalMonthIncomeRecording' : Array<CurrencyAggregatedAmount>,
  'totalVisitsCountEvents' : bigint,
  'totalVisitsCountPodcast' : bigint,
}
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createIncomeRecord' : ActorMethod<[IncomeRecordInput], bigint>,
  'deleteAllIncomeRecords' : ActorMethod<[], undefined>,
  'getAllIncomeRecords' : ActorMethod<[], Array<IncomeRecord>>,
  'getAllMonthlyReportsForYear' : ActorMethod<[bigint], Array<StudioReport>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIncomeRecord' : ActorMethod<[bigint], [] | [IncomeRecord]>,
  'getMonthlyReport' : ActorMethod<[bigint, bigint], StudioReport>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestRole' : ActorMethod<[RoleRequest], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePodcastDetails' : ActorMethod<[bigint, Podcast], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];