/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CurrencyAggregatedAmount {
    currency: Currency;
    amount: bigint;
}
export type Timestamp = bigint;
export interface RecordingStudioSession {
    sessionType: string;
    sessionLengthInMinutes: bigint;
    recordingArtistsOrPodcasts: string;
    paymentAmount: MonetaryAmount;
    purposeOfSession: string;
}
export interface RoleRequest {
    passcode?: string;
    requestedRole: AppRole;
}
export interface Event {
    payedInFull: boolean;
    finalPaymentRequestSent: boolean;
    paymentAmount: MonetaryAmount;
    finalPaymentsConfirmed: boolean;
    eventName: string;
}
export interface IncomeRecordInput {
    serviceType: string;
    visitorPhoneNumber: string;
    podcast?: Podcast;
    email: string;
    payedInFull: boolean;
    event?: Event;
    recordingSession?: RecordingStudioSession;
    idNumber: string;
    visitorName: string;
    address: string;
    photoVideoShoots?: PhotoOrVideoShoots;
    paymentAmount: MonetaryAmount;
}
export interface PhotoOrVideoShoots {
    purposeOfShoot: string;
    primaryPhotographer: string;
    shootingHour: bigint;
    sessionLengthInMinutes: bigint;
    shootType: string;
    recordingArtistsOrPodcasts: string;
    primaryVideographer: string;
    paymentAmount: MonetaryAmount;
}
export interface IncomeRecord {
    serviceType: string;
    visitorPhoneNumber: string;
    podcast?: Podcast;
    email: string;
    payedInFull: boolean;
    event?: Event;
    recordingSession?: RecordingStudioSession;
    idNumber: string;
    visitorName: string;
    address: string;
    timestamp: Timestamp;
    photoVideoShoots?: PhotoOrVideoShoots;
    paymentAmount: MonetaryAmount;
}
export interface Guest {
    name: string;
    guestType: GuestType;
    phoneNumber: string;
}
export interface StudioReport {
    totalMonthIncomeEvents: Array<CurrencyAggregatedAmount>;
    totalVisitedCount: bigint;
    totalMonthIncomePhotoVideo: Array<CurrencyAggregatedAmount>;
    totalVisitsCountPhotoVideo: bigint;
    totalVisitsCountRecording: bigint;
    totalMonthIncomePodcast: Array<CurrencyAggregatedAmount>;
    totalMonthIncome: Array<CurrencyAggregatedAmount>;
    totalMonthIncomeRecording: Array<CurrencyAggregatedAmount>;
    totalVisitsCountEvents: bigint;
    totalVisitsCountPodcast: bigint;
}
export interface MonetaryAmount {
    currency: Currency;
    amount: bigint;
}
export interface UserProfile {
    name: string;
}
export interface Podcast {
    podcastName: string;
    hostName: string;
    guests: Array<Guest>;
}
export enum AppRole {
    Director = "Director",
    Reception = "Reception",
    Manager = "Manager"
}
export enum Currency {
    BWP = "BWP",
    EUR = "EUR",
    GBP = "GBP",
    USD = "USD",
    ZAR = "ZAR",
    ZMW = "ZMW",
    ZWG = "ZWG"
}
export enum GuestType {
    guest = "guest",
    cohost = "cohost",
    assistant = "assistant"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createIncomeRecord(record: IncomeRecordInput): Promise<bigint>;
    deleteAllIncomeRecords(): Promise<void>;
    getAllIncomeRecords(): Promise<Array<IncomeRecord>>;
    getAllMonthlyReportsForYear(year: bigint): Promise<Array<StudioReport>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIncomeRecord(id: bigint): Promise<IncomeRecord | null>;
    getMonthlyReport(year: bigint, month: bigint): Promise<StudioReport>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    requestRole(roleRequest: RoleRequest): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePodcastDetails(recordId: bigint, podcast: Podcast): Promise<void>;
}
import type { AppRole as _AppRole, Currency as _Currency, CurrencyAggregatedAmount as _CurrencyAggregatedAmount, Event as _Event, Guest as _Guest, GuestType as _GuestType, IncomeRecord as _IncomeRecord, IncomeRecordInput as _IncomeRecordInput, MonetaryAmount as _MonetaryAmount, PhotoOrVideoShoots as _PhotoOrVideoShoots, Podcast as _Podcast, RecordingStudioSession as _RecordingStudioSession, RoleRequest as _RoleRequest, StudioReport as _StudioReport, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createIncomeRecord(arg0: IncomeRecordInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createIncomeRecord(to_candid_IncomeRecordInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIncomeRecord(to_candid_IncomeRecordInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAllIncomeRecords(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllIncomeRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllIncomeRecords();
            return result;
        }
    }
    async getAllIncomeRecords(): Promise<Array<IncomeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncomeRecords();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncomeRecords();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMonthlyReportsForYear(arg0: bigint): Promise<Array<StudioReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMonthlyReportsForYear(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMonthlyReportsForYear(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomeRecord(arg0: bigint): Promise<IncomeRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeRecord(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeRecord(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyReport(arg0: bigint, arg1: bigint): Promise<StudioReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReport(arg0, arg1);
                return from_candid_StudioReport_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReport(arg0, arg1);
            return from_candid_StudioReport_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async requestRole(arg0: RoleRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRole(to_candid_RoleRequest_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRole(to_candid_RoleRequest_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updatePodcastDetails(arg0: bigint, arg1: Podcast): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePodcastDetails(arg0, to_candid_Podcast_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePodcastDetails(arg0, to_candid_Podcast_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CurrencyAggregatedAmount_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CurrencyAggregatedAmount): CurrencyAggregatedAmount {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Currency_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Currency): Currency {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_GuestType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuestType): GuestType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Guest_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Guest): Guest {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_IncomeRecord_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeRecord): IncomeRecord {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_MonetaryAmount_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MonetaryAmount): MonetaryAmount {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PhotoOrVideoShoots_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhotoOrVideoShoots): PhotoOrVideoShoots {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Podcast_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Podcast): Podcast {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RecordingStudioSession_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordingStudioSession): RecordingStudioSession {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_StudioReport_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudioReport): StudioReport {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Podcast]): Podcast | null {
    return value.length === 0 ? null : from_candid_Podcast_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Event | null {
    return value.length === 0 ? null : from_candid_Event_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecordingStudioSession]): RecordingStudioSession | null {
    return value.length === 0 ? null : from_candid_RecordingStudioSession_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhotoOrVideoShoots]): PhotoOrVideoShoots | null {
    return value.length === 0 ? null : from_candid_PhotoOrVideoShoots_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IncomeRecord]): IncomeRecord | null {
    return value.length === 0 ? null : from_candid_IncomeRecord_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: string;
    visitorPhoneNumber: string;
    podcast: [] | [_Podcast];
    email: string;
    payedInFull: boolean;
    event: [] | [_Event];
    recordingSession: [] | [_RecordingStudioSession];
    idNumber: string;
    visitorName: string;
    address: string;
    timestamp: _Timestamp;
    photoVideoShoots: [] | [_PhotoOrVideoShoots];
    paymentAmount: _MonetaryAmount;
}): {
    serviceType: string;
    visitorPhoneNumber: string;
    podcast?: Podcast;
    email: string;
    payedInFull: boolean;
    event?: Event;
    recordingSession?: RecordingStudioSession;
    idNumber: string;
    visitorName: string;
    address: string;
    timestamp: Timestamp;
    photoVideoShoots?: PhotoOrVideoShoots;
    paymentAmount: MonetaryAmount;
} {
    return {
        serviceType: value.serviceType,
        visitorPhoneNumber: value.visitorPhoneNumber,
        podcast: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.podcast)),
        email: value.email,
        payedInFull: value.payedInFull,
        event: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.event)),
        recordingSession: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.recordingSession)),
        idNumber: value.idNumber,
        visitorName: value.visitorName,
        address: value.address,
        timestamp: value.timestamp,
        photoVideoShoots: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.photoVideoShoots)),
        paymentAmount: from_candid_MonetaryAmount_n36(_uploadFile, _downloadFile, value.paymentAmount)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    podcastName: string;
    hostName: string;
    guests: Array<_Guest>;
}): {
    podcastName: string;
    hostName: string;
    guests: Array<Guest>;
} {
    return {
        podcastName: value.podcastName,
        hostName: value.hostName,
        guests: from_candid_vec_n28(_uploadFile, _downloadFile, value.guests)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    guestType: _GuestType;
    phoneNumber: string;
}): {
    name: string;
    guestType: GuestType;
    phoneNumber: string;
} {
    return {
        name: value.name,
        guestType: from_candid_GuestType_n31(_uploadFile, _downloadFile, value.guestType),
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    payedInFull: boolean;
    finalPaymentRequestSent: boolean;
    paymentAmount: _MonetaryAmount;
    finalPaymentsConfirmed: boolean;
    eventName: string;
}): {
    payedInFull: boolean;
    finalPaymentRequestSent: boolean;
    paymentAmount: MonetaryAmount;
    finalPaymentsConfirmed: boolean;
    eventName: string;
} {
    return {
        payedInFull: value.payedInFull,
        finalPaymentRequestSent: value.finalPaymentRequestSent,
        paymentAmount: from_candid_MonetaryAmount_n36(_uploadFile, _downloadFile, value.paymentAmount),
        finalPaymentsConfirmed: value.finalPaymentsConfirmed,
        eventName: value.eventName
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currency: _Currency;
    amount: bigint;
}): {
    currency: Currency;
    amount: bigint;
} {
    return {
        currency: from_candid_Currency_n38(_uploadFile, _downloadFile, value.currency),
        amount: value.amount
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sessionType: string;
    sessionLengthInMinutes: bigint;
    recordingArtistsOrPodcasts: string;
    paymentAmount: _MonetaryAmount;
    purposeOfSession: string;
}): {
    sessionType: string;
    sessionLengthInMinutes: bigint;
    recordingArtistsOrPodcasts: string;
    paymentAmount: MonetaryAmount;
    purposeOfSession: string;
} {
    return {
        sessionType: value.sessionType,
        sessionLengthInMinutes: value.sessionLengthInMinutes,
        recordingArtistsOrPodcasts: value.recordingArtistsOrPodcasts,
        paymentAmount: from_candid_MonetaryAmount_n36(_uploadFile, _downloadFile, value.paymentAmount),
        purposeOfSession: value.purposeOfSession
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    purposeOfShoot: string;
    primaryPhotographer: string;
    shootingHour: bigint;
    sessionLengthInMinutes: bigint;
    shootType: string;
    recordingArtistsOrPodcasts: string;
    primaryVideographer: string;
    paymentAmount: _MonetaryAmount;
}): {
    purposeOfShoot: string;
    primaryPhotographer: string;
    shootingHour: bigint;
    sessionLengthInMinutes: bigint;
    shootType: string;
    recordingArtistsOrPodcasts: string;
    primaryVideographer: string;
    paymentAmount: MonetaryAmount;
} {
    return {
        purposeOfShoot: value.purposeOfShoot,
        primaryPhotographer: value.primaryPhotographer,
        shootingHour: value.shootingHour,
        sessionLengthInMinutes: value.sessionLengthInMinutes,
        shootType: value.shootType,
        recordingArtistsOrPodcasts: value.recordingArtistsOrPodcasts,
        primaryVideographer: value.primaryVideographer,
        paymentAmount: from_candid_MonetaryAmount_n36(_uploadFile, _downloadFile, value.paymentAmount)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMonthIncomeEvents: Array<_CurrencyAggregatedAmount>;
    totalVisitedCount: bigint;
    totalMonthIncomePhotoVideo: Array<_CurrencyAggregatedAmount>;
    totalVisitsCountPhotoVideo: bigint;
    totalVisitsCountRecording: bigint;
    totalMonthIncomePodcast: Array<_CurrencyAggregatedAmount>;
    totalMonthIncome: Array<_CurrencyAggregatedAmount>;
    totalMonthIncomeRecording: Array<_CurrencyAggregatedAmount>;
    totalVisitsCountEvents: bigint;
    totalVisitsCountPodcast: bigint;
}): {
    totalMonthIncomeEvents: Array<CurrencyAggregatedAmount>;
    totalVisitedCount: bigint;
    totalMonthIncomePhotoVideo: Array<CurrencyAggregatedAmount>;
    totalVisitsCountPhotoVideo: bigint;
    totalVisitsCountRecording: bigint;
    totalMonthIncomePodcast: Array<CurrencyAggregatedAmount>;
    totalMonthIncome: Array<CurrencyAggregatedAmount>;
    totalMonthIncomeRecording: Array<CurrencyAggregatedAmount>;
    totalVisitsCountEvents: bigint;
    totalVisitsCountPodcast: bigint;
} {
    return {
        totalMonthIncomeEvents: from_candid_vec_n49(_uploadFile, _downloadFile, value.totalMonthIncomeEvents),
        totalVisitedCount: value.totalVisitedCount,
        totalMonthIncomePhotoVideo: from_candid_vec_n49(_uploadFile, _downloadFile, value.totalMonthIncomePhotoVideo),
        totalVisitsCountPhotoVideo: value.totalVisitsCountPhotoVideo,
        totalVisitsCountRecording: value.totalVisitsCountRecording,
        totalMonthIncomePodcast: from_candid_vec_n49(_uploadFile, _downloadFile, value.totalMonthIncomePodcast),
        totalMonthIncome: from_candid_vec_n49(_uploadFile, _downloadFile, value.totalMonthIncome),
        totalMonthIncomeRecording: from_candid_vec_n49(_uploadFile, _downloadFile, value.totalMonthIncomeRecording),
        totalVisitsCountEvents: value.totalVisitsCountEvents,
        totalVisitsCountPodcast: value.totalVisitsCountPodcast
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    guest: null;
} | {
    cohost: null;
} | {
    assistant: null;
}): GuestType {
    return "guest" in value ? GuestType.guest : "cohost" in value ? GuestType.cohost : "assistant" in value ? GuestType.assistant : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BWP: null;
} | {
    EUR: null;
} | {
    GBP: null;
} | {
    USD: null;
} | {
    ZAR: null;
} | {
    ZMW: null;
} | {
    ZWG: null;
}): Currency {
    return "BWP" in value ? Currency.BWP : "EUR" in value ? Currency.EUR : "GBP" in value ? Currency.GBP : "USD" in value ? Currency.USD : "ZAR" in value ? Currency.ZAR : "ZMW" in value ? Currency.ZMW : "ZWG" in value ? Currency.ZWG : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncomeRecord>): Array<IncomeRecord> {
    return value.map((x)=>from_candid_IncomeRecord_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Guest>): Array<Guest> {
    return value.map((x)=>from_candid_Guest_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudioReport>): Array<StudioReport> {
    return value.map((x)=>from_candid_StudioReport_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CurrencyAggregatedAmount>): Array<CurrencyAggregatedAmount> {
    return value.map((x)=>from_candid_CurrencyAggregatedAmount_n50(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_Currency_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): _Currency {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Event_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): _Event {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_GuestType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuestType): _GuestType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Guest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Guest): _Guest {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_IncomeRecordInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncomeRecordInput): _IncomeRecordInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MonetaryAmount_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MonetaryAmount): _MonetaryAmount {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PhotoOrVideoShoots_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhotoOrVideoShoots): _PhotoOrVideoShoots {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Podcast_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Podcast): _Podcast {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RecordingStudioSession_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordingStudioSession): _RecordingStudioSession {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_RoleRequest_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoleRequest): _RoleRequest {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    payedInFull: boolean;
    finalPaymentRequestSent: boolean;
    paymentAmount: MonetaryAmount;
    finalPaymentsConfirmed: boolean;
    eventName: string;
}): {
    payedInFull: boolean;
    finalPaymentRequestSent: boolean;
    paymentAmount: _MonetaryAmount;
    finalPaymentsConfirmed: boolean;
    eventName: string;
} {
    return {
        payedInFull: value.payedInFull,
        finalPaymentRequestSent: value.finalPaymentRequestSent,
        paymentAmount: to_candid_MonetaryAmount_n14(_uploadFile, _downloadFile, value.paymentAmount),
        finalPaymentsConfirmed: value.finalPaymentsConfirmed,
        eventName: value.eventName
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currency: Currency;
    amount: bigint;
}): {
    currency: _Currency;
    amount: bigint;
} {
    return {
        currency: to_candid_Currency_n16(_uploadFile, _downloadFile, value.currency),
        amount: value.amount
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sessionType: string;
    sessionLengthInMinutes: bigint;
    recordingArtistsOrPodcasts: string;
    paymentAmount: MonetaryAmount;
    purposeOfSession: string;
}): {
    sessionType: string;
    sessionLengthInMinutes: bigint;
    recordingArtistsOrPodcasts: string;
    paymentAmount: _MonetaryAmount;
    purposeOfSession: string;
} {
    return {
        sessionType: value.sessionType,
        sessionLengthInMinutes: value.sessionLengthInMinutes,
        recordingArtistsOrPodcasts: value.recordingArtistsOrPodcasts,
        paymentAmount: to_candid_MonetaryAmount_n14(_uploadFile, _downloadFile, value.paymentAmount),
        purposeOfSession: value.purposeOfSession
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    purposeOfShoot: string;
    primaryPhotographer: string;
    shootingHour: bigint;
    sessionLengthInMinutes: bigint;
    shootType: string;
    recordingArtistsOrPodcasts: string;
    primaryVideographer: string;
    paymentAmount: MonetaryAmount;
}): {
    purposeOfShoot: string;
    primaryPhotographer: string;
    shootingHour: bigint;
    sessionLengthInMinutes: bigint;
    shootType: string;
    recordingArtistsOrPodcasts: string;
    primaryVideographer: string;
    paymentAmount: _MonetaryAmount;
} {
    return {
        purposeOfShoot: value.purposeOfShoot,
        primaryPhotographer: value.primaryPhotographer,
        shootingHour: value.shootingHour,
        sessionLengthInMinutes: value.sessionLengthInMinutes,
        shootType: value.shootType,
        recordingArtistsOrPodcasts: value.recordingArtistsOrPodcasts,
        primaryVideographer: value.primaryVideographer,
        paymentAmount: to_candid_MonetaryAmount_n14(_uploadFile, _downloadFile, value.paymentAmount)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: string;
    visitorPhoneNumber: string;
    podcast?: Podcast;
    email: string;
    payedInFull: boolean;
    event?: Event;
    recordingSession?: RecordingStudioSession;
    idNumber: string;
    visitorName: string;
    address: string;
    photoVideoShoots?: PhotoOrVideoShoots;
    paymentAmount: MonetaryAmount;
}): {
    serviceType: string;
    visitorPhoneNumber: string;
    podcast: [] | [_Podcast];
    email: string;
    payedInFull: boolean;
    event: [] | [_Event];
    recordingSession: [] | [_RecordingStudioSession];
    idNumber: string;
    visitorName: string;
    address: string;
    photoVideoShoots: [] | [_PhotoOrVideoShoots];
    paymentAmount: _MonetaryAmount;
} {
    return {
        serviceType: value.serviceType,
        visitorPhoneNumber: value.visitorPhoneNumber,
        podcast: value.podcast ? candid_some(to_candid_Podcast_n5(_uploadFile, _downloadFile, value.podcast)) : candid_none(),
        email: value.email,
        payedInFull: value.payedInFull,
        event: value.event ? candid_some(to_candid_Event_n12(_uploadFile, _downloadFile, value.event)) : candid_none(),
        recordingSession: value.recordingSession ? candid_some(to_candid_RecordingStudioSession_n18(_uploadFile, _downloadFile, value.recordingSession)) : candid_none(),
        idNumber: value.idNumber,
        visitorName: value.visitorName,
        address: value.address,
        photoVideoShoots: value.photoVideoShoots ? candid_some(to_candid_PhotoOrVideoShoots_n20(_uploadFile, _downloadFile, value.photoVideoShoots)) : candid_none(),
        paymentAmount: to_candid_MonetaryAmount_n14(_uploadFile, _downloadFile, value.paymentAmount)
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    passcode?: string;
    requestedRole: AppRole;
}): {
    passcode: [] | [string];
    requestedRole: _AppRole;
} {
    return {
        passcode: value.passcode ? candid_some(value.passcode) : candid_none(),
        requestedRole: to_candid_AppRole_n57(_uploadFile, _downloadFile, value.requestedRole)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    podcastName: string;
    hostName: string;
    guests: Array<Guest>;
}): {
    podcastName: string;
    hostName: string;
    guests: Array<_Guest>;
} {
    return {
        podcastName: value.podcastName,
        hostName: value.hostName,
        guests: to_candid_vec_n7(_uploadFile, _downloadFile, value.guests)
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    guestType: GuestType;
    phoneNumber: string;
}): {
    name: string;
    guestType: _GuestType;
    phoneNumber: string;
} {
    return {
        name: value.name,
        guestType: to_candid_GuestType_n10(_uploadFile, _downloadFile, value.guestType),
        phoneNumber: value.phoneNumber
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuestType): {
    guest: null;
} | {
    cohost: null;
} | {
    assistant: null;
} {
    return value == GuestType.guest ? {
        guest: null
    } : value == GuestType.cohost ? {
        cohost: null
    } : value == GuestType.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): {
    BWP: null;
} | {
    EUR: null;
} | {
    GBP: null;
} | {
    USD: null;
} | {
    ZAR: null;
} | {
    ZMW: null;
} | {
    ZWG: null;
} {
    return value == Currency.BWP ? {
        BWP: null
    } : value == Currency.EUR ? {
        EUR: null
    } : value == Currency.GBP ? {
        GBP: null
    } : value == Currency.USD ? {
        USD: null
    } : value == Currency.ZAR ? {
        ZAR: null
    } : value == Currency.ZMW ? {
        ZMW: null
    } : value == Currency.ZWG ? {
        ZWG: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    Director: null;
} | {
    Reception: null;
} | {
    Manager: null;
} {
    return value == AppRole.Director ? {
        Director: null
    } : value == AppRole.Reception ? {
        Reception: null
    } : value == AppRole.Manager ? {
        Manager: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Guest>): Array<_Guest> {
    return value.map((x)=>to_candid_Guest_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
